# Generated by Django 5.2.6 on 2026-06-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ['-started']},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
    ]
