# Generated by Django 5.2.6 on 2026-06-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('credits', models.PositiveIntegerField(default=3)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
